### ISSUE TITLE
Justify the use of this particular benchmark

### ISSUE THREAD

**Issue by JJ** [mariosky/RandomAWS#1]
As indicated by the first reviewer:
```
My main concern
about this study is the selection of the benchmark problems; concretely,
the OneMax with 128 bits is a very trivial one, and it does not make
sense to solve it in a parallel environment. The contribution of the
paper would gain interest if some hard real-world problems were studied
instead of classical benchmarks ones.
```

**Comment by mariosky** [comment]
Added: 
Although the OneMax problem may not justify the use of a distributed implementation, as we can argue that it can be solved in a short time by using a single desktop computer, on the other hand, it offers several advantages as a benchmark for new architectures. First, is a well-known problem with several studies on parameters,  running time analyses, and distributed implementation issues.  The drawback of using a benchmark that is not representative of real-world problems is that experimental results may be only applicable to problems similar to OneMax, where genetic operators are well suited for the search in a solution space without deceptive or very large landscapes.  

We need to add the appropriate references.
