### ISSUE TITLE
Address second referee

### ISSUE THREAD

**Issue by JJ** [mariosky/RandomAWS#2]
Mainly, this:
```
- Redesign the experimental validation to be able to properly validate or invalidate
the hypothesis.
- Use additional benchmark functions. Since authors want to attain general
conclusions, additional functions are required.
```

**Comment by mariosky** [comment]
We can't do more experiments easily, those were done in AWS using VMs since then I canceled my account.  But I can give it a look, these are general suggestions.

**Comment by mariosky** [comment]
I don't know if this comment was from an earlier version, we tested with One Max, but also Griewank and Sheffer.
