### ISSUE TITLE
Minor issues reviewer 2

### ISSUE THREAD

**Issue by JJ** [mariosky/RandomAWS#4]
- Authors state "distributed and asynchronous EAs have started to become common only
recently". I am not sure about it. It is true that now is more common, but these
kinds of scheme have been around us now for several decades.
- distributed process -> processes
- Authors related Island Models with synchronous systems, but there are also
asynchronous island-based models.
- Caption of Table one is not correct.
- Results show times and/or evaluations to reach an optimal solution. What happens
if the optimal solution is not found? What is an optimal solution? i.e. what is the
accuracy applied?
- The sentence that starts with "Figure 5 compares the approaches..." is not complete.

**Comment by JJ** [comment]
So we need to address this, right?

**Comment by mariosky** [comment]
Yes, they are minor corrections I think.
